joLog=function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b]);console.log(a.join(" "))};Function.prototype.extend=function(a,b){this.prototype=new a;if(b)for(var c in b)this.prototype[c]=b[c]};if(typeof Function.prototype.bind==="undefined")Function.prototype.bind=function(a){var b=this;return function(){return b.apply(a,arguments)}};if(typeof HTMLElement==="undefined")HTMLElement=Object;if(typeof console==="undefined"||typeof console.log!=="function")console={log:function(){}};
jo={platform:"webkit",version:"0.3.0",useragent:["ipad","iphone","webos","bada","android","opera","chrome","safari","mozilla","gecko","explorer"],debug:false,setDebug:function(a){this.debug=a},flag:{stopback:false},load:function(){joDOM.enable();this.loadEvent=new joSubject(this);this.unloadEvent=new joSubject(this);document.body.onMouseDown=function(c){c.preventDefault()};document.body.onDragStart=function(c){c.preventDefault()};if(typeof navigator=="object"&&navigator.userAgent)for(var a=navigator.userAgent.toLowerCase(),
b=0;b<this.useragent.length;b++)if(a.indexOf(this.useragent[b])>=0){this.platform=this.useragent[b];break}if(joEvent){a=document.createElement("div");b="ontouchstart"in a;if(!b){a.setAttribute("ontouchstart","return;");b=typeof a.ontouchstart==="function"}joEvent.touchy=b;a=null}joGesture&&joGesture.load();a=joScroller.prototype;if(typeof document.body.style.webkitTransition==="undefined")if(typeof document.body.style.MozTransition!=="undefined"){a.transitionEnd="transitionend";a.setPosition=function(c,
d,e){e.style.MozTransform="translate("+c+"px,"+d+"px)"}}else if(typeof document.body.style.msTransform!=="undefined"){a.transitionEnd="transitionend";a.setPosition=function(c,d,e){e.style.msTransform="translate("+c+"px,"+d+"px)"}}else if(typeof document.body.style.OTransition!=="undefined"){a.transitionEnd="otransitionend";a.setPosition=function(c,d,e){e.style.OTransform="translate("+c+"px,"+d+"px)"}}else{a.velocity=0;a.bump=0;a.transitionEnd="transitionend";a.setPosition=function(c,d,e){if(this.vertical)e.style.top=
d+"px";if(this.horizontal)e.style.left=c+"px"}}joLog("Jo",this.version,"loaded for",this.platform,"environment");this.loadEvent.fire()},tagMap:{},tagMapLoaded:false,initTagMap:function(){if(!this.tagMapLoaded){var a=this.tagMap;a.JOVIEW=joView;a.BODY=joScreen;for(var b in window){var c=window[b];if(typeof c==="function"&&c.prototype&&typeof c.prototype.tagName!=="undefined"&&c.prototype instanceof joView){var d=c.prototype.tagName.toUpperCase();if(c.prototype.type){a[d]||(a[d]={});a[d][c.prototype.type]=
c}else a[d]=c}}}},getPlatform:function(){return this.platform},matchPlatform:function(a){return a.indexOf(this.platform)>=0},getVersion:function(){return this.version},getLanguage:function(){return this.language}};
joDOM={enabled:false,get:function(a){if(typeof a==="string")return document.getElementById(a);else if(typeof a==="object")return a instanceof joView?a.container:a},remove:function(a){a.parentNode&&a.parentNode.removeChild(a)},enable:function(){this.enabled=true},getParentWithin:function(a,b){for(;a.parentNode!==window&&a.parentNode!==b;)a=a.parentNode;return a},addCSSClass:function(a,b){a=joDOM.get(a);if(typeof a.className!=="undefined"){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==
b)return;c.push(b);a.className=c.join(" ")}else a.className=b},removeCSSClass:function(a,b,c){a=joDOM.get(a);if(typeof a.className!=="undefined"){for(var d=a.className.split(/\s+/),e=0,f=d.length;e<f;e++)if(d[e]==b){if(f==1)a.className="";else{d.splice(e,e);a.className=d.join(" ")}return}if(c){d.push(b);a.className=d.join(" ")}}else a.className=b},toggleCSSClass:function(a,b){this.removeCSSClass(a,b,true)},create:function(a,b){if(!this.enabled)return null;if(typeof a==="object"&&typeof a.tagName===
"string"){var c=document.createElement(a.tagName);a.className&&this.setStyle(c,a.className)}else{c=document.createElement(a);b&&this.setStyle(c,b)}return c},setStyle:function(a,b){if(typeof b==="string")a.className=b;else if(typeof b==="object")for(var c in b)switch(c){case "id":case "className":a[c]=b[c];break;default:a.style[c]=b[c]}else if(typeof b!=="undefined")throw"joDOM.setStyle(): unrecognized type for style argument; must be object or string.";},applyCSS:function(a,b){b&&document.body.removeChild(b);
var c=joDOM.create("jostyle");c.innerHTML="<style>"+a+"</style>";document.body.appendChild(c);return c},removeCSS:function(a){document.body.removeChild(a)},loadCSS:function(a,b){var c=b?b:joDOM.create("link");c.rel="stylesheet";c.type="text/css";c.href=a+(jo.debug?"?"+joTime.timestamp():"");b||document.body.appendChild(c);return c}};joCSSRule=function(a){this.setData(a)};
joCSSRule.prototype={container:null,setData:function(a){this.data=a||"";this.enable()},clear:function(){this.setData()},disable:function(){joDOM.removeCSS(this.container)},enable:function(){this.container=joDOM.applyCSS(this.data,this.container)}};
joEvent={eventMap:{mousedown:"touchstart",mousemove:"touchmove",mouseup:"touchend",mouseout:"touchcancel"},touchy:false,getTarget:function(a){if(!a)a=window.event;return a.target?a.target:a.srcElement},capture:function(a,b,c,d,e){this.on(a,b,c,d,e,true)},on:function(a,b,c,d,e,f){function g(h){if(h.touches&&h.touches.length==1){var i=h.touches[0];h.pageX=i.pageX;h.pageY=i.pageY;h.screenX=i.screenX;h.screenY=i.screenY}d?c.call(d,h,e):c(h,e)}if(!c||!a)return false;if(this.touchy)if(this.eventMap[b])b=
this.eventMap[b];a=joDOM.get(a);c=c;e=e||"";g.capture=f||false;window.addEventListener?a.addEventListener(b,g,f||false):a.attachEvent("on"+b,g);return g},remove:function(a,b,c){a.removeEventListener(b,c,c.capture)},stop:function(a){if(a.stopPropagation)a.stopPropagation();else a.cancelBubble=true},preventDefault:function(a){a.preventDefault()},block:function(a){if(window.event)a=window.event;if(typeof a.target=="undefined")a.target=a.srcElement;switch(a.target.nodeName.toLowerCase()){case "input":case "textarea":return true;
default:return false}}};joSubject=function(a){this.subscriptions=[];this.subject=a};
joSubject.prototype={last:-1,subscribe:function(a,b,c){if(!a)return false;a={call:a};if(b)a.observer=b;if(c)a.data=c;this.subscriptions.push(a);return this.subject},unsubscribe:function(a,b){if(!a)return false;for(var c=0,d=this.subscriptions.length;c<d;c++){var e=this.subscriptions[c];if(e.call===a&&(typeof e.observer==="undefined"||e.observer===b)){this.subscriptions.splice(c,1);break}}return this.subject},resume:function(a){this.last!=-1&&this.fire(a,true);return this.subject},fire:function(a,
b){if(typeof a==="undefined")a="";var c=b?this.last||0:0;this.last=-1;for(var d=this.subscriptions.length;c<d;c++){var e=this.subscriptions[c],f=typeof e.data!=="undefined"?e.data:null;e.observer?e.call.call(e.observer,a,this.subject,f):e.call(a,this.subject,f);if(e.capture){this.last=c+1;break}}return this.subject},capture:function(a,b,c){if(!a)return false;a={call:a,capture:true};if(b)a.observer=b;if(c)a.data=c;this.subscriptions.unshift(a);return this.subject},release:function(a,b){return this.unsubscribe(a,
b)}};var SEC=1E3,MIN=60*SEC,HOUR=60*MIN,DAY=24*HOUR;joTime={timestamp:function(){return new Date/1}};function joDefer(a,b,c,d){c||(c=100);b||(b=this);return window.setTimeout(function(){a.call(b,d)},c)}joYield=joDefer;joCache={cache:{},set:function(a,b,c){if(b)this.cache[a]={call:b,context:c||this}},get:function(a){var b=this.cache[a]||null;if(b){if(!b.view)b.view=b.call(b.context,b.call);return b.view}else return new joView("View not found: "+a)}};
joChain=function(){this.queue=[];this.active=false;this.addEvent=new joSubject("add",this);this.startEvent=new joSubject("start",this);this.stopEvent=new joSubject("stop",this);this.nextEvent=new joSubject("next",this);this.stop();this.delay=100};
joChain.prototype={add:function(a,b,c){b||(b=this);c||(c="");this.queue.push({call:a,context:b,data:c});this.active&&!this.timer&&this.next()},start:function(){this.active=true;this.startEvent.fire();this.next()},stop:function(){this.active=false;this.timer!=null&&window.clearTimeout(this.timer);this.timer=null;this.stopEvent.fire()},next:function(){var a=this.queue.shift();if(a){this.nextEvent.fire(a);a.call.call(a.context,a.data);this.timer=this.queue.length?joEvent.yield(this.next,this,this.delay):
null}else this.timer=null}};joClipboard={data:"",get:function(){return joPreference.get("joClipboardData")||this.data},set:function(a){this.data=a;joPreference.set("joClipboardData")}};joDataSource=function(a){this.changeEvent=new joSubject(this);this.errorEvent=new joSubject(this);if(typeof a!=="undefined")this.setData(a);else this.data=""};
joDataSource.prototype={autoSave:true,data:null,setQuery:function(a){this.query=a},setAutoSave:function(a){this.autoSave=a;return this},setData:function(a){var b=this.data;this.data=a;a!==b&&this.changeEvent.fire(a)},getData:function(){return this.data},getDataCount:function(){return this.getData().length},getPageCount:function(){return this.pageSize?Math.floor(this.getData().length/this.pageSize)+1:1},getPage:function(a){a=a*this.pageSize;var b=a+this.pageSize;if(b>this.getData().length)b=this.getData().length;
if(a<0)a=0;return this.data.slice(a,b)},refresh:function(){},setPageSize:function(a){this.pageSize=a},getPageSze:function(){return this.pageSize},load:function(a){this.data=a;this.changeEvent.fire(a)},error:function(a){this.errorEvent.fire(a)}};joRecord=function(a){joDataSource.call(this,a)};
joRecord.extend(joDataSource,{delegate:{},link:function(a){return this.getDelegate(a)},getDelegate:function(a){this.delegate[a]||(this.delegate[a]=new joProperty(this,a));return this.delegate[a]},getProperty:function(a){return this.data[a]},setProperty:function(a,b){if(this.data[a]!==b){this.data[a]=b;this.changeEvent.fire(this);this.autoSave&&this.save();return this}},load:function(){console.log("TODO: extend the load() method");return this},save:function(){console.log("TODO: extend the save() method");
return this}});joProperty=function(a,b){joDataSource.call(this);this.changeEvent=new joSubject(this);a.changeEvent.subscribe(this.onSourceChange,this);this.datasource=a;this.p=b};joProperty.extend(joDataSource,{setData:function(a){this.datasource&&this.datasource.setProperty(this.p,a);return this},getData:function(){if(!this.datasource)return null;return this.datasource.getProperty(this.p)},onSourceChange:function(){this.changeEvent.fire(this.getData())}});
joDatabase=function(a,b){this.openEvent=new joEvent.Subject(this);this.closeEvent=new joEvent.Subject(this);this.errorEvent=new joEvent.Subject(this);this.datafile=a;this.size=b||256E3;this.db=null};
joDatabase.prototype={open:function(){if(this.db=openDatabase(this.datafile,"1.0",this.datafile,this.size))this.openEvent.fire();else{joLog("DataBase Error",this.db);this.errorEvent.fire()}},close:function(){this.db.close();this.closeEvent.fire()},now:function(a){var b=new Date;a&&b.setDate(b.valueOf()+a*1E3*60*60*24);return b.format("yyyy-mm-dd")}};
joSQLDataSource=function(a,b,c){this.db=a;this.query=typeof b=="undefined"?"":b;this.args=typeof c=="undefined"?[]:c;this.changeEvent=new joEvent.subject(this);this.errorEvent=new joEvent.subject(this)};
joSQLDataSource.prototype={setDatabase:function(a){this.db=a},setQuery:function(a){this.query=a},setData:function(a){this.data=a;this.changeEvent.fire()},clear:function(){this.data=[];this.changeEvent.fire()},setParameters:function(a){this.args=a},execute:function(a,b){this.setQuery(a||"");this.setParameters(b);this.query&&this.refresh()},refresh:function(){function a(g,h){c.data=[];for(var i=0,j=h.rows.length;i<j;i++){var k=h.rows.item(i);c.data.push(k)}c.changeEvent.fire(c.data)}function b(){joLog("SQL error",
f,"argument count",d.length);c.errorEvent.fire()}if(this.db){var c=this;if(arguments.length)for(var d=[],e=0;e<arguments.length;e++)d.push(arguments[e]);else d=this.args;var f=this.query;this.db.db.transaction(function(g){g.executeSql(f,d,a,b)})}else this.errorEvent.fire()}};joFileSource=function(a,b){this.changeEvent=new joSubject(this);this.errorEvent=new joSubject(this);b&&this.setTimeout(b);a&&this.setQuery(a)};
joFileSource.extend(joDataSource,{baseurl:"",query:"",load:function(){joFile(this.baseurl+this.query,this.callBack,this)},callBack:function(a,b){b?this.errorEvent.fire(b):this.setData(a)}});
joFile=function(a,b,c,d){function e(){if(b)c?b.call(c,null,true):b(true,null,true)}var f=new XMLHttpRequest;if(!f)return e();d||(d=60*SEC);var g=d>0?setTimeout(e,d):null;f.open("GET",a,true);f.onreadystatechange=function(){if(g)g=clearTimeout(g);if(f.readyState==4){var h=f.responseText;if(b)c?b.call(c,h,0):b(0,h,0)}};f.onError=e;f.send(null)};
function joScript(a,b,c){function d(f){if(b)c?b.call(c,f,a):b(f,a);document.body.removeChild(e);e=null}var e=joDOM.create("script");if(e){e.onload=function(){d(false)};e.onerror=function(){d(true)};e.src=a;document.body.appendChild(e)}}joPreference=joRecord;joYQL=function(a){joDataSource.call(this);this.setQuery(a)};
joYQL.extend(joDataSource,{baseurl:"http://query.yahooapis.com/v1/public/yql?",format:"json",query:"",exec:function(){var a=this.baseurl+"q="+encodeURIComponent(this.query)+"&format="+this.format+"&callback="+joDepot(this.load,this);joScript(a,this.callBack,this)},load:function(a){var b=a.query&&a.query.results&&a.query.results.item;if(b){this.data=b;this.changeEvent.fire(b)}else this.errorEvent.fire(a)},callBack:function(a){a&&this.errorEvent.fire()}});joDepotCall=[];
joDepot=function(a,b){joDepotCall.push(function(c){b?a.call(b,c):a(c)});return"joDepotCall["+(joDepotCall.length-1)+"]"};joInterface=function(a){jo.initTagMap();return this.get(a)};
joInterface.prototype={get:function(a){function b(g){if(g){var h="";if(g.childNodes&&g.firstChild){var i=g.childNodes;h=[];for(var j=0,k=i.length;j<k;j++){var l=b(i[j]);l&&h.push(l)}}return c(g,h)}}function c(g,h){var i=g.tagName,j=g;if(jo.tagMap[i]){if(h instanceof Array&&h.length)if(h.length==1)h=h[0];if(h instanceof Text)h=g.nodeData;h||(h=g.value||g.checked||g.innerText||g.innerHTML);joView.setContainer=function(){this.container=g;return this};if(typeof jo.tagMap[i]==="function")var k=jo.tagMap[i];
else{k=g.type||g.getAttribute("type");k=jo.tagMap[i][k]}if(typeof k==="function")j=new k(h);else joLog("joInterface can't process ",i,"'type' attribute?")}if(g.id)d[g.id]=j;return j}a=joDOM.get(a);if(!a)a=document.body;var d={},e=joView.setContainer,f=joView.draw;b(a);joView.setContainer=e;joView.draw=f;return d}};joCollect={get:function(a){return new joInterface(a)}};joView=function(a){this.changeEvent=new joSubject(this);this.setContainer();a&&this.setData(a)};
joView.prototype={tagName:"joview",busyNode:null,container:null,data:null,getContainer:function(){return this.container},setContainer:function(a){this.container=joDOM.get(a);if(!this.container)this.container=this.createContainer();this.setEvents();return this},createContainer:function(){return joDOM.create(this)},clear:function(){this.data="";if(this.container)this.container.innerHTML="";this.changeEvent.fire()},setData:function(a){this.data=a;this.refresh();return this},getData:function(){return this.data},
refresh:function(){if(!this.container||typeof this.data=="undefined")return 0;this.container.innerHTML="";this.draw();this.changeEvent.fire(this.data)},draw:function(){this.container.innerHTML=this.data},setStyle:function(a){joDOM.setStyle(this.container,a);return this},attach:function(a){if(!this.container)return this;(joDOM.get(a)||document.body).appendChild(this.container);return this},detach:function(a){if(!this.container)return this;a=joDOM.get(a)||document.body;this.container&&this.container.parentNode===
a&&a.removeChild(this.container);return this},setEvents:function(){}};joContainer=function(){joView.apply(this,arguments)};
joContainer.extend(joView,{tagName:"jocontainer",title:null,getContent:function(){return this.container.childNodes},setTitle:function(a){this.title=a;return this},setData:function(a){this.data=a;this.refresh();return this},activate:function(){},deactivate:function(){},push:function(a){if(typeof a==="object")if(a instanceof Array)for(var b=0;b<a.length;b++)this.push(a[b]);else if(a instanceof joView&&a.container!==this.container)this.container.appendChild(a.container);else a instanceof HTMLElement&&
this.container.appendChild(a);else{b=document.createElement("div");b.innerHTML=a;this.container.appendChild(b)}},getTitle:function(){return this.title},refresh:function(){if(this.container)this.container.innerHTML="";this.draw();this.changeEvent.fire()},draw:function(){this.push(this.data)}});
joControl=function(a,b){this.selectEvent=new joSubject(this);this.enabled=true;if(typeof b!=="undefined"&&b!=null)if(b instanceof joDataSource)this.setValueSource(b);else this.value=b;if(a instanceof joDataSource){joView.call(this);this.setDataSource(a)}else joView.apply(this,arguments)};
joControl.extend(joView,{tagName:"jocontrol",value:null,setEvents:function(){joEvent.on(this.container,"click",this.onMouseDown,this);joEvent.on(this.container,"blur",this.onBlur,this);joEvent.on(this.container,"focus",this.onFocus,this)},onMouseDown:function(a){this.select(a)},select:function(a){a&&joEvent.stop(a);this.selectEvent.fire(this.data)},enable:function(){joDOM.removeCSSClass(this.container,"disabled");this.enabled=this.container.contentEditable=true;return this},disable:function(){joDOM.addCSSClass(this.container,
"disabled");this.enabled=this.container.contentEditable=false;return this},onFocus:function(a){joEvent.stop(a);joFocus.set(this)},onBlur:function(a){this.data=this.container.value?this.container.value:this.container.innerHTML;joEvent.stop(a);this.blur();this.changeEvent.fire(this.data)},focus:function(a){joDOM.addCSSClass(this.container,"focus");a||this.container.focus();return this},setValue:function(a){this.value=a;this.changeEvent.fire(a);return this},getValue:function(){return this.value},blur:function(){joDOM.removeCSSClass(this.container,
"focus");return this},setDataSource:function(a){this.dataSource=a;a.changeEvent.subscribe(this.setData,this);this.setData(a.getData()||null);this.changeEvent.subscribe(a.setData,a);return this},setValueSource:function(a){this.valueSource=a;a.changeEvent.subscribe(this.setValue,this);this.setValue(a.getData()||null);this.selectEvent.subscribe(a.setData,a);return this}});joButton=function(a,b){joControl.apply(this,arguments);if(b)this.container.className=b};
joButton.extend(joControl,{tagName:"jobutton",createContainer:function(){var a=joDOM.create(this.tagName);a&&a.setAttribute("tabindex","1");return a},enable:function(){this.container.setAttribute("tabindex","1");return joControl.prototype.enable.call(this)},disable:function(){this.container.removeAttribute("tabindex");return joControl.prototype.disable.call(this)}});joBusy=function(){joContainer.apply(this,arguments)};
joBusy.extend(joContainer,{tagName:"jobusy",draw:function(){this.container.innerHTML="";for(var a=0;a<9;a++)this.container.appendChild(joDom.create("jobusyblock"))},setMessage:function(a){this.message=a||""},setEvents:function(){return this}});joList=function(){this.setIndex=this.setValue;this.getIndex=this.getValue;joControl.apply(this,arguments)};
joList.extend(joControl,{tagName:"jolist",data:null,defaultMessage:"",lastNode:null,value:null,autoSort:false,setDefault:function(a){this.defaultMessage=a;if(typeof this.data==="undefined"||!this.data||!this.data.length)if(typeof a==="object"){this.innerHTML="";if(a instanceof joView)this.container.appendChild(a.container);else a instanceof HTMLElement&&this.container.appendChild(a)}else this.innerHTML=a;return this},draw:function(){var a="",b=0;if(typeof this.data==="undefined"||!this.data||!this.data.length){if(this.defaultMessage)this.container.innerHTML=
this.defaultMessage}else{for(var c=0,d=this.data.length;c<d;c++){var e=this.formatItem(this.data[c],c,b);if(e!=null){if(typeof e==="string")a+=e;else this.container.appendChild(e instanceof joView?e.container:e);++b}}if(a.length)this.container.innerHTML=a;this.value>=0&&this.setValue(this.value,true)}},deselect:function(){if(!(typeof this.container=="undefined"||!this.container.childNodes)){if(this.getNode(this.value))if(this.lastNode){joDOM.removeCSSClass(this.lastNode,"selected");this.value=null}return this}},
setValue:function(a,b){this.value=a;if(a!=null){if(typeof this.container==="undefined"||!this.container||!this.container.firstChild)return this;var c=this.getNode(this.value);if(c){this.lastNode&&joDOM.removeCSSClass(this.lastNode,"selected");joDOM.addCSSClass(c,"selected");this.lastNode=c}if(a>=0&&!b){this.fireSelect(a);this.changeEvent.fire(a)}return this}},getNode:function(a){return this.container.childNodes[a]},fireSelect:function(a){this.selectEvent.fire(a)},getValue:function(){return this.value},
onMouseDown:function(a){joEvent.stop(a);a=joEvent.getTarget(a);for(var b=-1;b==-1&&a!==this.container;){b=a.getAttribute("index")||-1;a=a.parentNode}b>=0&&this.setValue(b)},refresh:function(){this.autoSort&&this.sort();joControl.prototype.refresh.apply(this)},getNodeData:function(a){return this.data&&this.data.length&&a>=0&&a<this.data.length?this.data[a]:null},getLength:function(){return this.length||this.data.length||0},sort:function(){this.data.sort(this.compareItems)},getNodeIndex:function(a){a=
a.getAttribute("index");return typeof a!=="undefined"&&a!=null?parseInt(a):-1},formatItem:function(a,b){var c=document.createElement("jolistitem");c.innerHTML=a;c.setAttribute("index",b);return c},compareItems:function(a,b){return a>b?1:a==b?0:-1},setAutoSort:function(a){this.autoSort=a;return this},next:function(){this.getValue()<this.getLength()-1&&this.setValue(this.value+1)},prev:function(){this.getValue()>0&&this.setValue(this.value-1)}});joBusy=function(){joContainer.apply(this,arguments)};
joBusy.extend(joContainer,{tagName:"jobusy",draw:function(){this.container.innerHTML="";for(var a=0;a<9;a++)this.container.appendChild(joDom.create("jobusyblock"))},setMessage:function(a){this.message=a||""},setEvents:function(){return this}});joCaption=function(){joControl.apply(this,arguments)};joCaption.extend(joControl,{tagName:"jocaption"});joCard=function(){joContainer.apply(this,arguments)};joCard.extend(joContainer,{tagName:"jocard"});
joStack=function(){this.visible=false;joContainer.apply(this,arguments);if(this.data&&!(this.data instanceof Array))this.data=[this.data];else if(this.data.length>1)this.data=[this.data[0]];if(this.container&&this.container.firstChild)this.container.innerHTML="";this.setLocked(true);this.pushEvent=new joSubject(this);this.popEvent=new joSubject(this);this.homeEvent=new joSubject(this);this.showEvent=new joSubject(this);this.hideEvent=new joSubject(this);this.lastIndex=this.index=0;this.lastNode=null};
joStack.extend(joContainer,{tagName:"jostack",type:"fixed",eventset:false,data:[],setEvents:function(){},onClick:function(a){joEvent.stop(a)},forward:function(){if(this.index<this.data.length-1){this.index++;this.draw()}},back:function(){if(this.index>0){this.index--;this.draw()}},draw:function(){function a(){if(b){g.removeChild(b);joDOM.removeCSSClass(b,"next");joDOM.removeCSSClass(b,"prev")}if(d){h&&joEvent.remove(d,"webkitTransitionEnd",h);joDOM.removeCSSClass(d,"next");joDOM.removeCSSClass(d,
"prev")}}this.container||this.createContainer();if(this.data&&this.data.length){jo.flag.stopback=this.index?true:false;var b=this.lastNode,c=this.data[this.index]instanceof joView?this.data[this.index].container:this.data[this.index],d=this.getChildStyleContainer(c);if(d){if(this.index>this.lastIndex){var e="prev",f="next";joDOM.addCSSClass(d,f)}else if(this.index<this.lastIndex){e="next";f="prev";joDOM.addCSSClass(d,f)}this.appendChild(c);var g=this,h=null;joDefer(function(){if(typeof window.onwebkittransitionend!==
"undefined")h=joEvent.on(d,"webkitTransitionEnd",a,g);else joDefer(a,this,200);f&&d&&joDOM.removeCSSClass(d,f);e&&b&&joDOM.addCSSClass(b,e)},this,1);typeof this.data[this.index].activate!=="undefined"&&this.data[this.index].activate.call(this.data[this.index]);this.lastIndex=this.index;this.lastNode=d}}},appendChild:function(a){this.container.appendChild(a)},getChildStyleContainer:function(a){return a},getChild:function(){return this.container.firstChild},getContentContainer:function(){return this.container},
removeChild:function(a){a&&a.parentNode===this.container&&this.container.removeChild(a)},isVisible:function(){return this.visible},push:function(a){if(!(this.data&&this.data.length&&this.data[this.data.length-1]===a)){this.data.push(a);this.index=this.data.length-1;this.draw();this.pushEvent.fire(a)}},setLocked:function(a){this.locked=a?1:0},pop:function(){if(this.data.length>this.locked){var a=this.data.pop();this.index=this.data.length-1;this.draw();typeof a.deactivate==="function"&&a.deactivate.call(a);
this.data.length||this.hide()}this.data.length>0&&this.popEvent.fire()},home:function(){if(this.data&&this.data.length&&this.data.length>1){var a=this.data[0];if(a!==this.data[this.index]){this.data=[a];this.lastIndex=1;this.index=0;this.draw();this.popEvent.fire();this.homeEvent.fire()}}},showHome:function(){this.home();if(!this.visible){this.visible=true;joDOM.addCSSClass(this.container,"show");this.showEvent.fire()}},getTitle:function(){var a=this.data[this.index];return typeof a.getTitle==="function"?
a.getTitle():false},show:function(){if(!this.visible){this.visible=true;joDOM.addCSSClass(this.container,"show");joDefer(this.showEvent.fire,this.showEvent,500)}},hide:function(){if(this.visible){this.visible=false;joDOM.removeCSSClass(this.container,"show");joDefer(this.hideEvent.fire,this.hideEvent,500)}}});joScroller=function(){this.points=[];this.eventset=false;joContainer.apply(this,arguments)};
joScroller.extend(joContainer,{tagName:"joscroller",moved:false,inMotion:false,pacer:0,velocity:1.6,bump:50,top:0,mousemove:null,mouseup:null,transitionEnd:"webkitTransitionEnd",horizontal:0,vertical:1,setEvents:function(){joEvent.capture(this.container,"click",this.onClick,this);joEvent.on(this.container,"mousedown",this.onDown,this)},onFlick:function(){},onClick:function(a){if(this.moved){this.moved=false;joEvent.stop(a);joEvent.preventDefault(a)}},onDown:function(a){joEvent.stop(a);this.reset();
var b=this.container.firstChild;joDOM.removeCSSClass(b,"flick");joDOM.removeCSSClass(b,"flickback");joDOM.removeCSSClass(b,"flickfast");this.start=this.getMouse(a);this.points.unshift(this.start);this.inMotion=true;if(!this.mousemove){this.mousemove=joEvent.on(document.body,"mousemove",this.onMove,this);this.mouseup=joEvent.on(document.body,"mouseup",this.onUp,this)}},reset:function(){this.points=[];this.inMotion=this.moved=this.quickSnap=false},onMove:function(a){if(this.inMotion){joEvent.stop(a);
a.preventDefault();a=this.getMouse(a);var b=a.y-this.points[0].y,c=a.x-this.points[0].x;this.points.unshift(a);this.points.length>7&&this.points.pop();var d=this;this.timer=window.setTimeout(function(){d.points.length>1&&d.points.pop()},100);this.scrollBy(c,b,true);if(!this.moved&&this.points.length>3)this.moved=true}},onUp:function(a){if(this.inMotion){joEvent.remove(document.body,"mousemove",this.mousemove);joEvent.remove(document.body,"mouseup",this.mouseup);this.mousemove=null;this.inMotion=false;
joEvent.stop(a);this.getMouse(a);a=this.container.firstChild;for(var b=this.getTop(),c=this.getLeft(),d=0,e=0,f=0;f<this.points.length-1;f++){d+=this.points[f].y-this.points[f+1].y;e+=this.points[f].x-this.points[f+1].x}f=0-a.offsetHeight+this.container.offsetHeight-this.bump;var g=0-a.offsetWidth+this.container.offsetWidth-this.bump;if((Math.abs(d)>4||Math.abs(e)>4)&&!this.quickSnap){d=d*this.velocity*(a.offsetHeight/this.container.offsetHeight);e=e*this.velocity*(a.offsetWidth/this.container.offsetWidth);
d+b<f||d+b>0||e+c<g||e+c>0?joDOM.addCSSClass(a,"flickfast"):joDOM.addCSSClass(a,"flick");this.scrollBy(e,d,false)}else this.snapBack()}},getMouse:function(a){return{x:this.horizontal?a.screenX:0,y:this.vertical?a.screenY:0}},scrollBy:function(a,b){var c=this.container.firstChild,d=this.getTop(),e=this.getLeft(),f=Math.floor(d+b),g=Math.floor(e+a);if(!(this.vertical&&c.offsetHeight<=this.container.offsetHeight)){var h=0-c.offsetHeight+this.container.offsetHeight,i=0-c.offsetWidth+this.container.offsetWidth;
if(f>this.bump)f=this.bump;else if(f<h-this.bump)f=h-this.bump;if(g>this.bump)g=this.bump;else if(f<i-this.bump)g=i-this.bump;this.eventset=joEvent.on(c,this.transitionEnd,this.snapBack,this);if(d!=g||e!=f)this.moveTo(g,f)}},scrollTo:function(a,b){var c=this.container.firstChild;if(c){if(typeof a=="object"){if(a instanceof HTMLElement)var d=a;else if(a instanceof joView)d=a.container;var e=0-d.offsetTop;d=d.offsetHeight+80;a=f;var f=this.getTop();if(e-d<f-this.container.offsetHeight)a=e-d+this.container.offsetHeight;
if(a<e)a=e}if(a<0-c.offsetHeight)a=0-c.offsetHeight;else if(a>0)a=0;if(b){joDOM.removeCSSClass(c,"flick");joDOM.removeCSSClass(c,"flickback")}else joDOM.addCSSClass(c,"flick");this.moveTo(0,a)}},snapBack:function(){var a=this.container.firstChild,b=this.getTop(),c=this.getLeft(),d=b,e=c,f=0-a.offsetHeight+this.container.offsetHeight,g=0-a.offsetWidth+this.container.offsetWidth;this.eventset&&joEvent.remove(a,this.transitionEnd,this.eventset);joDOM.removeCSSClass(a,"flick");if(d>0)d=0;else if(d<f)d=
f;if(e>0)e=0;else if(e<g)e=g;if(e!=c||d!=b){joDOM.addCSSClass(a,"flickback");this.moveTo(e,d)}},setScroll:function(a,b){this.horizontal=a?1:0;this.vertical=b?1:0;return this},moveTo:function(a,b){var c=this.container.firstChild;if(c){this.setPosition(a*this.horizontal,b*this.vertical,c);c.jotop=b;c.joleft=a}},setPosition:function(a,b,c){c.style.webkitTransform="translate3d("+a+"px, "+b+"px, 0)"},getTop:function(){return this.container.firstChild.jotop||0},getLeft:function(){return this.container.firstChild.joleft||
0},setData:function(){joContainer.prototype.setData.apply(this,arguments)}});joDivider=function(){joView.apply(this,arguments)};joDivider.extend(joView,{tagName:"jodivider"});joExpando=function(){this.openEvent=new joSubject(this);this.closeEvent=new joSubject(this);joContainer.apply(this,arguments)};
joExpando.extend(joContainer,{tagName:"joexpando",draw:function(){if(this.data){joContainer.prototype.draw.apply(this,arguments);this.setToggleEvent()}},setEvents:function(){},setToggleEvent:function(){joEvent.on(this.container.childNodes[0],"click",this.toggle,this)},toggle:function(){this.container.className.indexOf("open")>=0?this.close():this.open()},open:function(){joDOM.addCSSClass(this.container,"open");this.openEvent.fire()},close:function(){joDOM.removeCSSClass(this.container,"open");this.closeEvent.fire()}});
joExpandoContent=function(){joContainer.apply(this,arguments)};joExpandoContent.extend(joContainer,{tagName:"joexpandocontent"});joExpandoTitle=function(){joControl.apply(this,arguments)};joExpandoTitle.extend(joControl,{tagName:"joexpandotitle",setData:function(){joView.prototype.setData.apply(this,arguments);this.draw()},draw:function(){this.container.innerHTML=this.data+"<joicon></joicon>"}});joFlexrow=function(){joContainer.apply(this,arguments)};joFlexrow.extend(joContainer,{tagName:"joflexrow"});
joFlexcol=function(){joContainer.apply(this,arguments)};joFlexcol.extend(joContainer,{tagName:"joflexcol"});joFocus={last:null,set:function(a){this.last&&this.last!==a&&this.last.blur();if(a&&a instanceof joControl){a.focus();this.last=a}},get:function(){return this.last},refresh:function(){this.last&&this.last.focus()},clear:function(){this.set()}};joFooter=function(){joContainer.apply(this,arguments)};joFooter.extend(joContainer,{tagName:"jofooter"});
joGesture={load:function(){this.upEvent=new joSubject(this);this.downEvent=new joSubject(this);this.leftEvent=new joSubject(this);this.rightEvent=new joSubject(this);this.forwardEvent=new joSubject(this);this.backEvent=new joSubject(this);this.homeEvent=new joSubject(this);this.closeEvent=new joSubject(this);this.activateEvent=new joSubject(this);this.deactivateEvent=new joSubject(this);this.setEvents()},setEvents:function(){joEvent.on(document.body,"keydown",this.onKeyDown,this);joEvent.on(document.body,
"keyup",this.onKeyUp,this);joEvent.on(document.body,"unload",this.closeEvent,this);joEvent.on(window,"activate",this.activateEvent,this);joEvent.on(window,"deactivate",this.deactivateEvent,this)},onKeyUp:function(a){if(!a)a=window.event;if(a.keyCode==18)this.altkey=false;else if(a.keyCode==27){if(jo.flag.stopback){joEvent.stop(a);joEvent.preventDefault(a)}this.backEvent.fire("back")}else if(this.altkey){joEvent.stop(a);switch(a.keyCode){case 37:this.leftEvent.fire("left");break;case 38:this.upEvent.fire("up");
break;case 39:this.rightEvent.fire("right");break;case 40:this.downEvent.fire("down");break;case 27:this.backEvent.fire("back");break;case 13:this.forwardEvent.fire("forward")}}},onKeyDown:function(a){if(!a)a=window.event;if(a.keyCode==27){joEvent.stop(a);joEvent.preventDefault(a)}else if(a.keyCode==13&&joFocus.get()instanceof joInput)joEvent.stop(a);else if(a.keyCode==18)this.altkey=true}};joGroup=function(){joContainer.apply(this,arguments)};joGroup.extend(joContainer,{tagName:"jogroup"});
joHTML=function(){joControl.apply(this,arguments)};joHTML.extend(joControl,{tagName:"johtml",setEvents:function(){joEvent.on(this.container,"click",this.onClick,this)},onClick:function(a){function b(d){if(!d)return null;if(d.href)return d;return typeof d.parentNode!=="undefined"&&d.parentNode!==c?b(d.parentNode):null}joEvent.stop(a);joEvent.preventDefault(a);var c=this.container;(a=b(joEvent.getTarget(a)))&&this.selectEvent.fire(a.href)}});joInput=function(){joControl.apply(this,arguments)};
joInput.extend(joControl,{tagName:"input",type:"text",setData:function(a){if(a!==this.data){this.data=a;if(typeof this.container.value!=="undefined")this.container.value=a;else this.container.innerHTML=a;this.changeEvent.fire(this.data)}},getData:function(){return typeof this.container.value!=="undefined"?this.container.value:this.container.innerHTML},enable:function(){this.container.setAttribute("tabindex","1");joControl.prototype.enable.call(this)},disable:function(){this.container.removeAttribute("tabindex");
joControl.prototype.disable.call(this)},createContainer:function(){var a=joDOM.create(this);if(a){a.setAttribute("type","text");a.setAttribute("tabindex","1");a.contentEditable=this.enabled;return a}},setEvents:function(){joControl.prototype.setEvents.call(this);joEvent.on(this.container,"keydown",this.onKeyDown,this)},onKeyDown:function(a){if(a.keyCode==13){a.preventDefault();joEvent.stop(a)}return false},draw:function(){if(this.container.value)this.value=this.data;else this.innerHTML=this.value},
onMouseDown:function(a){joEvent.stop(a);this.focus()},storeData:function(){this.data=this.getData();this.dataSource&&this.dataSource.set(this.value)}});joLabel=function(){joControl.apply(this,arguments)};joLabel.extend(joControl,{tagName:"jolabel"});joMenu=function(){joList.apply(this,arguments)};
joMenu.extend(joList,{tagName:"jomenu",itemTagName:"jomenuitem",value:null,fireSelect:function(a){typeof this.data[a].id!=="undefined"&&this.data[a].id?this.selectEvent.fire(this.data[a].id):this.selectEvent.fire(a)},formatItem:function(a,b){var c=joDOM.create(this.itemTagName);c.setAttribute("index",b);if(typeof a==="object"){c.innerHTML=a.title;if(a.icon){c.style.backgroundImage="url("+a.icon+");";joDOM.addCSSClass(c,"icon")}}else c.innerHTML=a;return c}});
joOption=function(){joMenu.apply(this,arguments)};joOption.extend(joMenu,{tagName:"jooption",itemTagName:"jooptionitem"});joPasswordInput=function(){joInput.apply(this,arguments)};joPasswordInput.extend(joInput,{className:"password",type:"password"});joPopup=function(){this.showEvent=new joSubject(this);this.hideEvent=new joSubject(this);joContainer.apply(this,arguments)};
joPopup.extend(joContainer,{tagName:"jopopup",setEvents:function(){joEvent.on(this.container,"mousedown",this.onClick,this)},onClick:function(a){joEvent.stop(a)},hide:function(){joEvent.on(this.container,"webkitTransitionEnd",this.onHide,this);this.container.className="hide"},onHide:function(){this.hideEvent.fire()},show:function(){this.container.className="show";this.showEvent.fire()}});
joScreen=function(){this.resizeEvent=new joSubject(this);this.menuEvent=new joSubject(this);this.activateEvent=new joSubject(this);this.deactivateEvent=new joSubject(this);this.backEvent=new joSubject(this);this.forwardEvent=new joSubject(this);joContainer.apply(this,arguments)};
joScreen.extend(joContainer,{tagName:"screen",setupEvents:function(){joEvent.on(window,"resize",this.resizeEvent.fire,this);joEvent.on(window,"appmenushow",this.menuEvent.fire,this);joEvent.on(window,"activate",this.activateEvent.fire,this);joEvent.on(window,"deactivate",this.deactivateEvent.fire,this);joEvent.on(window,"back",this.backEvent.fire,this)},createContainer:function(){return document.body},showPopup:function(a){if(this.popup)this.popup.setData(a);else this.shim=new joShim(new joFlexcol(["&nbsp",
this.popup=new joPopup(a),"&nbsp"]));this.shim.show();this.popup.show()},hidePopup:function(){this.shim&&this.shim.hide()},alert:function(a,b,c,d){function e(j){j||(j={label:"OK"});var k=new joButton(j.label);k.selectEvent.subscribe(function(){j.action&&j.action.call(j.context);i.hidePopup();if(g)d?g.call(d):g()},j.context||i);f.push(k)}var f=[],g;d=typeof d==="object"?d:null;if(typeof c==="object")if(c instanceof Array)for(var h=0;h<c.length;h++)e(c[h]);else e(c);else if(typeof c==="string")e({label:c});
else{if(typeof c==="function")g=c;e()}this.showPopup([new joTitle(a),new joHTML(b),f]);var i=this}});joShim=function(){this.showEvent=new joSubject(this);this.hideEvent=new joSubject(this);this.selectEvent=new joSubject(this);joContainer.apply(this,arguments)};
joShim.extend(joContainer,{tagName:"joshim",setEvents:function(){joEvent.on(this.container,"mousedown",this.onMouseDown,this)},onMouseDown:function(a){joEvent.stop(a);this.hide()},hide:function(){this.container.className="";joEvent.on(this.container,"webkitTransitionEnd",this.onHide,this)},show:function(){this.attach();this.container.className="show";joEvent.on(this.container,"webkitTransitionEnd",this.onShow,this);if(!this.lastParent)this.lastParent=document.body},onShow:function(){this.showEvent.fire()},
onHide:function(){this.detach();this.hideEvent.fire()}});joSound=function(a,b){this.endedEvent=new joSubject(this);this.errorEvent=new joSubject(this);if(typeof Audio!="undefined"){this.filename=a;this.audio=new Audio;this.audio.autoplay=false;if(this.audio){joDefer(function(){this.audio.src=a;this.audio.load()},this,5);this.setRepeatCount(b);joEvent.on(this.audio,"ended",this.onEnded,this)}}};
joSound.prototype={play:function(){this.audio&&this.audio.play()},onEnded:function(){this.endedEvent.fire(this.repeat);if(++this.repeat<this.repeatCount)this.play();else this.repeat=0},setRepeatCount:function(a){this.repeatCount=a;this.repeat=0},pause:function(){this.audio&&this.audio.pause()},rewind:function(){if(this.audio){try{this.audio.currentTime=0}catch(a){joLog("joSound: can't rewind...")}this.repeat=0}},stop:function(){this.pause();this.rewind();this.repeat=0},setVolume:function(a){if(!(!this.audio||
a<0||a>1))this.audio.volume=a}};joStackScroller=function(){this.scrollers=[new joScroller,new joScroller];this.scroller=this.scrollers[0];joStack.apply(this,arguments);this.scroller.attach(this.container)};
joStackScroller.extend(joStack,{type:"scroll",scrollerindex:1,scroller:null,scrollers:[],switchScroller:function(){this.scrollerindex=this.scrollerindex?0:1;this.scroller=this.scrollers[this.scrollerindex]},getLastScroller:function(){return this.scrollers[this.scrollerindex?0:1]},scrollTo:function(a){this.scroller.scrollTo(a)},scrollBy:function(a){this.scroller.scrollBy(a)},getChildStyleContainer:function(){return this.scroller.container},getContentContainer:function(){return this.scroller.container},
appendChild:function(a){var b=this.scroller;b.setData(a);this.container.appendChild(b.container)},getChild:function(){return this.scroller.container||null},forward:function(){this.index<this.data.length-1&&this.switchScroller();joStack.prototype.forward.call(this)},back:function(){this.index>0&&this.switchScroller();joStack.prototype.forward.call(this)},home:function(){if(this.data&&this.data.length&&this.data.length>1){this.switchScroller();joStack.prototype.home.call(this)}},push:function(a){if(!(this.data&&
this.data.length&&this.data[this.data.length-1]===a)){this.switchScroller();joDOM.removeCSSClass(a,"flick");joDOM.removeCSSClass(a,"flickback");this.scroller.setData(a);this.scroller.scrollTo(0,true);joStack.prototype.push.call(this,a)}},pop:function(){this.data.length>this.locked&&this.switchScroller();joStack.prototype.pop.call(this)}});joTabBar=function(){joList.apply(this,arguments)};
joTabBar.extend(joList,{tagName:"jotabbar",formatItem:function(a,b){var c=document.createElement("jotab");if(a.label)c.innerHTML=a.label;if(a.type)c.className=a.type;c.setAttribute("index",b);return c}});joTable=function(){joList.apply(this,arguments)};
joTable.extend(joList,{tagName:"jotable",formatItem:function(a,b){for(var c=document.createElement("tr"),d=0,e=a.length;d<e;d++){var f=document.createElement(b?"td":"th");f.innerHTML=a[d];f.setAttribute("index",b*e+d);c.appendChild(f)}return c},getNode:function(a){var b=this.getRow(a);a=this.getCol(a);return this.container.childNodes[b].childNodes[a]},getRow:function(a){if(typeof a=="undefined")a=this.getIndex();return Math.floor(a/this.data[0].length)},getCol:function(a){if(typeof a=="undefined")a=
this.getIndex();return a%this.data[0].length}});joTextarea=function(){joInput.apply(this,arguments)};joTextarea.extend(joInput,{tagName:"textarea",onKeyDown:function(){return false}});joTitle=function(){joView.apply(this,arguments)};joTitle.extend(joView,{tagName:"jotitle"});joToolbar=function(){joContainer.apply(this,arguments)};joToolbar.extend(joContainer,{tagName:"jotoolbar"});joForm=function(){joContainer.apply(this,arguments)};joForm.extend(joContainer,{tagName:"form"});
joDialog=function(a){joShim.call(this,new joFlexcol(["",(new joPopup(new joScroller(a))).setStyle("show"),""]))};joDialog.extend(joShim,{});joSelectList=function(){joList.apply(this,arguments)};joSelectList.extend(joList,{tagName:"joselectlist"});joNavbar=function(a){if(a)this.firstTitle=a;a=[this.titlebar=(new joView(a||"&nbsp;")).setStyle("title"),new joFlexrow([this.back=(new joBackButton("Back")).selectEvent.subscribe(this.back,this),""])];joContainer.call(this,a)};
joNavbar.extend(joContainer,{tagName:"jonavbar",stack:null,back:function(){this.stack&&this.stack.pop()},setStack:function(a){if(this.stack){this.stack.pushEvent.unsubscribe(this.update,this);this.stack.popEvent.unsubscribe(this.update,this)}if(a){this.stack=a;a.pushEvent.subscribe(this.update,this);a.popEvent.subscribe(this.update,this);this.refresh()}else this.stack=null},update:function(){if(this.stack){joDOM.removeCSSClass(this.back,"selected");joDOM.removeCSSClass(this.back,"focus");this.stack.data.length>
1?joDOM.addCSSClass(this.back,"active"):joDOM.removeCSSClass(this.back,"active");var a=this.stack.getTitle();typeof a==="string"?this.titlebar.setData(a):this.titlebar.setData(this.firstTitle)}},setTitle:function(a){this.titlebar.setData(a);this.firstTitle=a}});joBackButton=function(){joButton.apply(this,arguments)};joBackButton.extend(joButton,{tagName:"jobackbutton"});
joSelect=function(a,b){var c=b;if(b instanceof joDataSource)c=b.getData();c=[this.field=new joSelectTitle(c),this.list=new joSelectList(a,b)];this.field.setList(this.list);this.changeEvent=this.list.changeEvent;this.selectEvent=this.list.selectEvent;joExpando.call(this,c);this.container.setAttribute("tabindex",1);this.field.setData(this.list.value);this.list.selectEvent.subscribe(this.setValue,this)};
joSelect.extend(joExpando,{setValue:function(a,b){if(b){this.field.setData(a);this.close()}else this.field.setData(a)},getValue:function(){return this.list.getValue()},setEvents:function(){joControl.prototype.setEvents.call(this)},onBlur:function(a){joEvent.stop(a);joDOM.removeCSSClass(this,"focus");this.close()}});joSelectTitle=function(){joExpandoTitle.apply(this,arguments)};
joSelectTitle.extend(joExpandoTitle,{list:null,setList:function(a){this.list=a},setData:function(a){this.list?joExpandoTitle.prototype.setData.call(this,this.list.getNodeData(a)||"Select..."):joExpandoTitle.prototype.setData.call(this,a)}});joToggle=function(a){joControl.call(this,a)};
joToggle.extend(joControl,{tagName:"jotoggle",button:null,labels:["Off","On"],setLabels:function(a){if(a instanceof Array)this.labels=a;else if(arguments.length==2)this.labels=arguments;this.draw();return this},select:function(a){a&&joEvent.stop(a);this.setData(this.data?false:true)},onBlur:function(a){joEvent.stop(a);this.blur()},draw:function(){if(this.container){if(!this.container.firstChild){this.button=joDOM.create("div");this.container.appendChild(this.button)}this.button.innerHTML=this.labels[this.data?
1:0];this.data?joDOM.addCSSClass(this.container,"on"):joDOM.removeCSSClass(this.container,"on")}}});
